### PR TITLE
Add configuration to show top bar with organisation logo and user info

### PR DESCRIPTION
**Pull request by romanhaa**
This PR allows showing a top bar with an organisation logo and optionally information about the currently logged in user. Merging this into our fork means we no longer have to commit this into project repositories.

### CODE REVIEW

**Comment by romanhaa** [comment]
Implementing the top bar through a React component as opposed to injecting it directly into the frontend fixes two minor issues: (1) the arrow at the bottom of the home page (see below) is cut off because the page content is pushed down by the top bar and (2) the scrolling issue (when scrolling down from the top of the page, there is a small jump).

Screenshot 2022-10-19 at 10 47 05

**Comment by fedde-s** [comment]
I think the previous approach, while avoiding the awkwardness of patching things that should have been configurable into the upstream code before building, caused a third layout issue where the bar would obscure widgets with absolute or fixed positioning at the very top of the page, such as the back-to-top button in the navbar of OT Platform profile pages and the button to reset the expanded view of a molecular 3d structure.

**Comment by romanhaa** [comment]
Yes, I vaguely remember that as well.

**Comment by romanhaa** [comment]
Maybe we can already implement it as a shared component between OTP and OTG, I think that would be ideal.

**Comment by fedde-s** [comment]
@romanhaa 
> Maybe we can already implement it as a shared component between OTP and OTG

I already assumed that that would be the next action after merging this one, if not the next commit before doing so :smile:  I imagine that releases of OTP and OTG usually use different snapshots of the ot-ui-apps code so we don't deploy the same commit (this PR still points to the one that was used in the previous release of the platform), but maintaining different sets of patches between the two apps sounds needlessly complicated.

**Comment by fedde-s** [comment]
So far, (rebased on 0.2.5/docker for platform 22.09) I've still found two issues of the same scale as the ones it is supposed to fix: the top icon in the back-to-top button in the profile page navbar is still obscured by the top bar and the 3d structure view (in the ProtVista section on target profile pages now moves _in front_ of the top bar even when just scrolling by it (rather than expanding to fill the window):
Screenshot showing the top bar obscuring the Home button in a scrolled-up navbar and not obscuring the 3d structure view

I'll start looking whether I can fix them.

**Comment by fedde-s** [comment]
I've addressed the issues I found. @romanhaa, would you have time to review the four added commits?

**Comment by fedde-s** [comment]
The last commit is a refactoring of the one before; to avoid rebase conflicts in the future, we should squash at least those two.

**Comment by romanhaa** [comment]
I rebased the commits on the `v0.2.10/docker` branch, changed the base branch accordingly, moved the top bar definition to the shared `ui` package and implemented the top bar in OTG.

**Comment by fedde-s** [comment]
Still working on the final test in OTG before squash-merging this in preparation for platform 23.02

**Review by fedde-s — APPROVED** [review]

**Pull request merged**
